// //go:build !ignore_autogenerated
// // +build !ignore_autogenerated

// // Code generated by deepcopy-gen. DO NOT EDIT.

package util

// import . "github.com/go-telegram-bot-api/telegram-bot-api/v5"

// // DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
// func (in *Update) DeepCopyInto(out *Update) {
// 	*out = *in
// 	if in.Message != nil {
// 		in, out := &in.Message, &out.Message
// 		*out = new(Message)
// 		(*in).DeepCopyInto(*out)
// 	}

// 	if in.EditedMessage != nil {
// 		in, out := &in.EditedMessage, &out.EditedMessage
// 		*out = new(Message)
// 		(*in).DeepCopyInto(*out)
// 	}
// 	if in.ChannelPost != nil {
// 		in, out := &in.ChannelPost, &out.ChannelPost
// 		*out = new(Message)
// 		(*in).DeepCopyInto(*out)
// 	}
// 	if in.EditedChannelPost != nil {
// 		in, out := &in.EditedChannelPost, &out.EditedChannelPost
// 		*out = new(Message)
// 		(*in).DeepCopyInto(*out)
// 	}
// 	if in.InlineQuery != nil {
// 		in, out := &in.InlineQuery, &out.InlineQuery
// 		*out = new(InlineQuery)
// 		(*in).DeepCopyInto(*out)
// 	}
// 	if in.ChosenInlineResult != nil {
// 		in, out := &in.ChosenInlineResult, &out.ChosenInlineResult
// 		*out = new(ChosenInlineResult)
// 		(*in).DeepCopyInto(*out)
// 	}
// 	if in.CallbackQuery != nil {
// 		in, out := &in.CallbackQuery, &out.CallbackQuery
// 		*out = new(CallbackQuery)
// 		(*in).DeepCopyInto(*out)
// 	}
// 	if in.ShippingQuery != nil {
// 		in, out := &in.ShippingQuery, &out.ShippingQuery
// 		*out = new(ShippingQuery)
// 		(*in).DeepCopyInto(*out)
// 	}
// 	if in.PreCheckoutQuery != nil {
// 		in, out := &in.PreCheckoutQuery, &out.PreCheckoutQuery
// 		*out = new(PreCheckoutQuery)
// 		(*in).DeepCopyInto(*out)
// 	}
// 	if in.Poll != nil {
// 		in, out := &in.Poll, &out.Poll
// 		*out = new(Poll)
// 		(*in).DeepCopyInto(*out)
// 	}
// 	if in.PollAnswer != nil {
// 		in, out := &in.PollAnswer, &out.PollAnswer
// 		*out = new(PollAnswer)
// 		(*in).DeepCopyInto(*out)
// 	}
// 	if in.MyChatMember != nil {
// 		in, out := &in.MyChatMember, &out.MyChatMember
// 		*out = new(ChatMemberUpdated)
// 		(*in).DeepCopyInto(*out)
// 	}
// 	if in.ChatMember != nil {
// 		in, out := &in.ChatMember, &out.ChatMember
// 		*out = new(ChatMemberUpdated)
// 		(*in).DeepCopyInto(*out)
// 	}
// 	if in.ChatJoinRequest != nil {
// 		in, out := &in.ChatJoinRequest, &out.ChatJoinRequest
// 		*out = new(ChatJoinRequest)
// 		(*in).DeepCopyInto(*out)
// 	}
// 	return
// }

// // DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Update.
// func (in *Update) DeepCopy() *Update {
// 	if in == nil {
// 		return nil
// 	}
// 	out := new(Update)
// 	in.DeepCopyInto(out)
// 	return out
// }
